### ISSUE TITLE
Sentence typo

### ISSUE THREAD

**Issue by ritwik12** [PlasmaPy/plasmapy.github.io#11]
> A community developed An open source community developed Python 3.6+ package for plasma physics in the early stages of development. 

This sentence is not proper I guess, are these tags?

**Comment by StanczakDominik** [comment]
I'm not seeing this anywhere on the site :confused: I'm going to close this for now, but if you could point us towards the typo (preferably with a link!), we would be all to happy to find and annihilate it :smile:

**Comment by ritwik12** [comment]
@StanczakDominik  Lines 12-13
https://github.com/PlasmaPy/plasmapy.github.io/blob/src/web/pages/index.html

**Comment by namurphy** [comment]
It looks like [we fixed this typo](https://github.com/PlasmaPy/plasmapy.github.io/commit/8c3951d27523ea069d19ccab752bb498b26ecd57#diff-a663918433e2d8e9bede07b330d0130d) already, though it may have still been showing up on the website if we didn't rebuild it. Thank you for taking the time to let us know about it, and please let us know if you find any other typos!
