### ISSUE TITLE
Remove references to Twitter account

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/plasmapy.github.io#153]
There are a few places that reference PlasmaPy's (formerly) Twitter account.  It has, for ...various reasons, fallen out of use. We should remove the references to Twitter, which I think are all in `conf.py`.

Note that the pull request should be made to `src` rather than `main`.  

This would be a great issue for someone who hasn't contributed before.  Thank you!

**Comment by Lavinia225** [comment]
I can work on! I'll read the contribution file and begin.
