### ISSUE TITLE
Announce NSF CSSI grant and update funding acknowledgements

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/plasmapy.github.io#28]
The NSF CSSI grant is important news, so it would be well worth adding an announcement on our front page (as well as sending out an email to the list).  

While doing this, we should update the funding acknowledgements to reflect the NSF CSSI grant.  This would be essentially the same as https://github.com/PlasmaPy/PlasmaPy/issues/679, but for the website.  For the text, we can cut and paste the updated acknowledgements from https://github.com/PlasmaPy/PlasmaPy/pull/688.  It'd probably be good to create a funding announcements page.  

I'll assign this to myself, and hopefully we can get this merged before the APS DPP meeting begins on October 21.  This is probably of interest to @tulasinandan and @rocco8773 too.

**Comment by StanczakDominik** [comment]
Right, can I help in any way?
