### ISSUE TITLE
Add a search feature to the top menu

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/plasmapy.github.io#32]
This looks to be done by defining the [`SEARCH_FORM` variable in `conf.py`](https://github.com/PlasmaPy/plasmapy.github.io/blob/a53224c20999871e2b17e48c870a2213cb9b2864/web/conf.py#L1218-L1256).

The suggested definitions in `conf.py` do not have a clean implementation, so we need to do some more investigation.

**Comment by StanczakDominik** [comment]
What do you mean by "do not have a clean implementation"? Do they visually look bad?

**Comment by rocco8773** [comment]
Yes, it's visually bad and re-directs you away form our own website.  The search bar is not placed cleanly within the top menu.

**Comment by StanczakDominik** [comment]
Ah... Well, I'm not sure I know of anything that does local website search while staying a static website. I'm not sure but I think custom search may be out of Nikola's reach.

Visuals could be improved more simply, though.

**Comment by rocco8773** [comment]
closed by #38
