### ISSUE TITLE
Consider using Jekyll instead of Nikola if we do a major redesign

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/plasmapy.github.io#33]
If we end of making major structural changes to our website, it would be worth revisiting the question of which static website generator we end up using.  We're using [Nikola](https://getnikola.com/) now, while [Jekyll](https://jekyllrb.com/) is one of the most widely used ones.   In a comparison between [Jekyll vs. Nikola](https://www.slant.co/versus/1002/1006/~nikola_vs_jekyll), Jekyll was recommended for most people.  If we don't end up making major design changes to our website, then it's likely more sensible to stick with Nikola.  The purpose of this issue is pretty much to bookmark this question for later if/when we do decide to do a substantial redesign, so that we keep the option open for Jekyll.  (I don't have a well enough informed opinion yet.)

Jekyll is built to work with GitHub Pages, and I personally preferred the documentation for Jekyll (note: this opinion has low signal to noise).  Jekyll is more widely used and has more maintainers, which means that web searches to figure out how to do things will be more fruitful with Jekyll.  Plus, it is more likely that newcomers will be familiar with Jekyll than with Nikola (though probably most will be familiar with neither), and experience with Jekyll may be more useful to students who move on to different projects after this.  That Nikola is written in Python is beneficial for us, while Jekyll is based on Ruby.

**Comment by StanczakDominik** [comment]
I do remember that I couldn't get Jekyll and Ruby in general to work, as a Python person.

I don't think a website's source is something we should be too worried about newcomers having to handle, though!

**Comment by namurphy** [comment]
Closing this as there's naught to do for it, and things seem to be working well with Nikola for the time being.

**Comment by namurphy** [comment]
It sounds like [Hugo](https://gohugo.io/) would be a really good option nowadays too.
