### ISSUE TITLE
Add material to front page

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/plasmapy.github.io#6]
Now that we have the framework for a webpage, we need to add content.  I've been looking at the [Astropy](http://www.astropy.org) and [SunPy](http://sunpy.org/) websites for ideas.  Some ideas for sections include:

* [x] Introduction and a mission statement
  * [x] Link to vision statement
* [ ] Becoming involved
  * [x] Matrix, Gitter, email list, biweekly telecons (with occasional tutorials)
  * [ ] Raise issues on GitHub (can help guide the development roadmap!)
  * [x] Contribute code
  * [x] Ways to contribute besides contributing code
* [x] Link to code of conduct
* [ ] Install PlasmaPy
* [ ] Learning PlasmaPy
  * [ ] Documentation Page
  * [ ] Tutorials repository
  * [ ] Link to conference posters on Zenodo
* [x] Acknowledging PlasmaPy

**Comment by RoberTnf** [comment]
I think that a few of this ideas are already covered:
- The becoming involved section is already covered in http://www.plasmapy.org/contribute/
- The code of conduct is here http://www.plasmapy.org/conduct/
- And for the last point, acknowledging PlasmaPy, what do you mean? 

Great ideas though!

**Comment by etiontdn** [comment]
I would like to help, but i never helped open source projects before so if you could, i would like some guidings
